Flake8:
  script:
    - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
    - ". ./prepare-and-run-flake8.sh pypvfmm test setup.py codegen_helpers.py"
  tags:
    - python3
  except:
    - tags

Python 3:
  script:
    - py_version=3
    - EXTRA_INSTALL="numpy mako pybind11"
    - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
    - ". ./build-and-test-py-project.sh"
  tags:
    - python3
    - latex
  except:
    - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 2.7:
  script:
    - export PY_EXE=python2.7
    - export EXTRA_INSTALL="numpy mako pybind11"
    - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
    - ". ./build-and-test-py-project.sh"
  tags:
    - python2.7
  except:
    - tags
  artifacts:
    reports:
      junit: test/pytest.xml
